#! /usr/bin/env ruby

require 'builder'
require 'fileutils'
require 'yaml'

def dir_blacklist
  ["css", "sass", "script"]
end

def useless?(f)
  f.start_with?("_") ||
    f.start_with?(".") ||
    !File.directory?(f) ||
    dir_blacklist.include?(f)
end

def get_gif_dirs
  # Dir.foreach("gif-library/**").map { |f| f unless useless?(f) }.compact
  Dir.glob('gif-library/**').select {|f| File.directory? f}
  # Dir.entries('gif-library').select {|entry| File.directory? File.join('gif-library',entry) and !(entry =='.' || entry == '..') }
end

def liquid_info_for_file(dir, filename)
  path = File.join(filename)
  {
    "path"          => path,
    "modified_time" => File.mtime(path).to_i,
    "extname"       => File.extname(path)
  }
end

list = Builder::XmlMarkup.new(
  target: File.open("_includes/site-index.html", 'w'),
  indent: 4,
  margin: 0
)

dirs  = get_gif_dirs
files = []

list.div(
    "class" => "gifCollection"
  ) do |builder|
  dirs.each do |dir|
    builder.div(
        "class" => "gifSet"
      ) do |dir_element|
      dir_element.h3(
        File.basename(dir),
        "class" => "gifSet-title"
      )
      dir_element.ul(
          "class" => "gifSet-list"
        ) do |ul|
        Dir.glob("#{dir}/**/*.gif") do |gif|
          files << liquid_info_for_file(dir, gif)
          ul.li(
              "class" => "gifSet-list-item  js-searchable"
            ) do |li|
            li.a(
              File.basename(gif),
              "href"  => gif,
              "class" => "gifLink"
            )
          end
        end
      end
    end
  end
end

FileUtils.mkdir_p("_data") unless File.directory?("_data")
File.open("_data/static_files.yml", 'w') { |f| f.write(YAML.dump(files)) }
